language: c

os:
  - linux
  - osx

git:
  depth: 1

script:
  - export PROJECT=$(echo $TRAVIS_REPO_SLUG | cut -d/ -f2-)
  - if [ $TRAVIS_OS_NAME = linux ]; then QLIBDIR=l64; elif [ $TRAVIS_OS_NAME = osx ]; then QLIBDIR=m64; else echo "unknown OS ('$TRAVIS_OS_NAME')" >&2; exit 1; fi; export QLIBDIR
  - make $QLIBDIR/p.so
  - tar czf ${PROJECT}_${TRAVIS_TAG}_${TRAVIS_OS_NAME}.tgz LICENSE p.q p.k $QLIBDIR/p.so

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: ${PROJECT}_${TRAVIS_TAG}_${TRAVIS_OS_NAME}.tgz
  skip_cleanup: true
  on:
    tags: true

jobs:
  include:
    - stage: docker
      sudo: required
      services:
        - docker
      script:
        - eval ${DOCKER_IMAGE:+docker build -t $DOCKER_IMAGE -f docker/Dockerfile .}
      deploy:
        provider: script
        script: eval ${DOCKER_IMAGE:+echo $DOCKER_API_KEY | docker login --username $DOCKER_USERNAME --password-stdin && docker push $DOCKER_IMAGE}
        skip_cleanup: true
        on:
          tags: true
